- title: Digital Equity & Empowerment Project
  years: May 2025 — Present
  position: Founding Member
  institution: Georgia Institute of Technology
  location: "Atlanta, GA"
  description: Design and lead workshops on AI safety and responsible use for Atlanta-based youths
  institution-url: http://gatech.edu

- title: Stamps Scholars National Convention
  years: Sep. 2022 — Apr. 2023
  position: Web Developer & Administrator
  institution: Georgia Institute of Technology
  location: "Atlanta, GA"
  description: Managed website development and administration for a convention with 700 attendees from 40 schools
  institution-url: http://gatech.edu